config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/rcstar/openQxD:
      branch: master
      repo: https://gitlab.com/rcstar/openQxD
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-rose-anteater.sh
        container: qc.acc_scanty-corn-centipede
  QC.Doc:
    repos:
      gitlab.com/rcstar/openQxD find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-viridian-coyote.sh
        container: qc.doc_skinny-rose-uguisu
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-linen-gibbon.sh
        container: qc.doc_ugly-rose-robin
  QC.Lic:
    repos:
      gitlab.com/rcstar/openQxD licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-silver-dollar.sh
        container: qc.lic_trippy-vermilion-coral
  QC.Ver:
    repos:
      gitlab.com/rcstar/openQxD get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-olive-hedgehog.sh
        container: qc.ver_bumpy-mustard-whippet
timeout: 1800
