config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/rcstar/openQxD:
      branch: master
      repo: https://gitlab.com/rcstar/openQxD
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-buff-olm.sh
        container: qc.acc_nerdy-smalt-macaque
  QC.Doc:
    repos:
      gitlab.com/rcstar/openQxD find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-flax-cuttlefish.sh
        container: qc.doc_shabby-eggplant-quail
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chocolate-argentino.sh
        container: qc.doc_blurry-persimmon-insect
  QC.Lic:
    repos:
      gitlab.com/rcstar/openQxD licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-crimson-turkey.sh
        container: qc.lic_lousy-plum-elephant
  QC.Ver:
    repos:
      gitlab.com/rcstar/openQxD get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amethyst-antelope.sh
        container: qc.ver_shaggy-lilac-birman
timeout: 1800
